sudo: false
language: ruby

jobs:
  include:
    - env: &adoc-latest ASCIIDOCTOR_VERSION=2.0.5
      rvm: &ruby-latest 2.7
    - env: *adoc-latest
      rvm: 2.6
    - env: *adoc-latest
      rvm: 2.5
    - env: *adoc-latest
      rvm: 2.4
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head

    - env: ASCIIDOCTOR_VERSION=1.5.8
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.7.1
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.7
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.6.2
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.6.1
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION=1.5.6
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

  allow_failures:
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head
    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

env:
  global:
    secure: "Ud9YaMRxL9hpEN5wMSQtqtFSWWA2XKobwqfqatGQBvJTb48Z5ehppT/BZBvFpk10SHNNL+x6Yn2YMDm6dcn/1uvAiEHK/nWmtXss9pC57UVcBiglnlkJxUxCxYacTfWaDj6J44lYscCgXbzmO68vsvVMPSchSzeeD2+o26PWAxreONqBKvMOkaGgqB1cVFnChkn+OOK8SvUv8C9eT4MMyixciWX8w9V5/aCHwo4yzmhU+2PNXMxD9kFnAx3pW8WZNFltSK/DHO31NkSKrD4cvxus4W+ahpErTczx8zSedT5ij37FiO3L7NrZj5AlQi3+TR+C+OPmVsba6HHiMdyN8h4FqwYNu2rv8oDn3dnvS9wMkdoXwYD5zntXhcY4fmfZ2liHEtXuGlwTf3sRjTBIz4LevoTTClogLzfvhJ7wzq+Xdiwlaq2jd7JWAzEjiOMTvbzpHSgopfnw8961joLGaaUkAMT2Mbuznm+kAhCJ69E7iigwdd1DS11TJrbsz/PDyZtOojTWfCZ9oRinM4KO32xzYeI1Vc/M6yj/C1kQqCi/G3rKf4UdcxPn2/R5xxjO3itInd8+qMSGEspJPbb7eBgzUJXQHjXqYQVM3JlNFnxHaH8WuyaQ2Y7mFYhcNeVeEwX0IUptJrKMs44icbu5qLpTsmYHcBTsoV1503y5RPY="  # CODACY_PROJECT_TOKEN

script:
  - bundle exec rake spec
  - bundle exec rake rubocop
  - bundle exec rake build:js

deploy:
  - provider: rubygems
    api_key:
      secure: "jztr6MjxlGHms1v10fI3+vSu3fZAj6FXPi8R/mZF0P/+TDJKls5SxRVW1PLnnfe6A2qvOEVoUpJw4fN/iXwpgBtUA1mzAurh8T3mJ6rrqjiW2cz2bvIVQ83MoNYsk2dP4xg+EYPCdAYzsm5IqQb++c9rJ9zR1Q3OVtuFhNIw4OAYjiROzwj1jWuy1QVYQ5GW3xFIMCF+RbJsadrs9td9nOHtxEjFjIHXneSMlR27fmLDiZ3AmaqFzGo5DfVtL4NebhVHPz8qCYSY8vsPZsb83Ov9tVtXW7cLWN4ruC2LA2DwiB6PfHhbrd7XRbUZJSH0z8b60bKaV9dMj7akFcZq/9WwcsADrbHo+3cwpHaIis3w8Fs7WOgauVUq5tgtO0mFoj6uJwfBS0WROwpsqqrEA4FNVvBn6aFi3TscpVostIG0bq4BMHsk7ruU+iOcUkLcZwza7t2Odyvtngv4niFD0dOaXv7kuAb7gmaCkMAWvxTSdImcbe7qlEUThUZft0wvMvMN+WWUDYf+vAamm9MEzEB5edt8Skp+2MOQdlleRvV9NPdZFCNJc5IIto/+OxbAyW8ti/r0/I08+gPX9AaOB9S3lchaaobeQ7esEq66ghTyeJxGgESQ1v40S4PNHkkdIBsKQegVYAtNE1vL3n/N5qLSlRzcLw5iz84bPZzPuOE="
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
  - provider: npm
    email: jakub@jirutka.cz
    api_key:
      secure: "lPyXyHAhGmrNFDV3h72olnqWAHEhYdUBAiDGqF4Rs204rlOG1e0onft0YZA13eNwllKbZFyahytgXnmDs9nnpiYber5n9E7ESMZeONhVb0slU1IzaJKd5RwAVBki2KaBNH9/LQJxuJg6bXhik2LAdBH98HIL+5b7ErHchM7nGIKiImY8sf5q4Sqw/LINCQl5w4f9fZpo3xuFJijXZcu9+JUg7KsNHdgRutcRY4hVkA9x78HZCAfxI4PQ+W8y0n4lmpzoMu0UPYMt9WTAeVGq37Ovonsfp1n96axrEnq2r8FZ6zC65CohxAuKUBE6p3a02lspyuTmaKUxDlDuQoroL88KFoXglS2wR26XD1VP9JZHErmX2epqj1cXoMNUxnhmH3eUWA0KpGKC42DgrqWkes2hCdoW5dLARojsads91ww1En/DPDFdMABl69hYkS5OqNLY81yVpo2NTWkqwbtFgdOsbwJzetj+MXO2McZ6WOFHk2zbw6bNyH8kZGYmaTwqtgYBzRhE11dbH4drrmTsubR0JnV9y6i1iCZGpwwrMWf5jxyQ7p1lBjSlcgqHYUvakHmPXPnpFBPYk4LRtaGMfuJIh5If5xBUpqI1MFI1vuHGIhz23NigkfaEcdzjKjp+Ldr2cxmMFMzGR7FMnEw3i+8i9yTRsNxhOu19dA5OOpM="  # 825a......3f7f
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
