sudo: false
language: ruby

jobs:
  include:
    - env: &adoc-latest ASCIIDOCTOR_VERSION=1.5.7.1
      rvm: &ruby-latest 2.5
    - env: *adoc-latest
      rvm: 2.4
    - env: *adoc-latest
      rvm: 2.3
    - env: *adoc-latest
      rvm: jruby-9.1
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head

    - env: ASCIIDOCTOR_VERSION=1.5.6
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION=1.5.6.1
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION=1.5.6.2
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.7
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

  allow_failures:
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head
    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

env:
  global:
    secure: "Ud9YaMRxL9hpEN5wMSQtqtFSWWA2XKobwqfqatGQBvJTb48Z5ehppT/BZBvFpk10SHNNL+x6Yn2YMDm6dcn/1uvAiEHK/nWmtXss9pC57UVcBiglnlkJxUxCxYacTfWaDj6J44lYscCgXbzmO68vsvVMPSchSzeeD2+o26PWAxreONqBKvMOkaGgqB1cVFnChkn+OOK8SvUv8C9eT4MMyixciWX8w9V5/aCHwo4yzmhU+2PNXMxD9kFnAx3pW8WZNFltSK/DHO31NkSKrD4cvxus4W+ahpErTczx8zSedT5ij37FiO3L7NrZj5AlQi3+TR+C+OPmVsba6HHiMdyN8h4FqwYNu2rv8oDn3dnvS9wMkdoXwYD5zntXhcY4fmfZ2liHEtXuGlwTf3sRjTBIz4LevoTTClogLzfvhJ7wzq+Xdiwlaq2jd7JWAzEjiOMTvbzpHSgopfnw8961joLGaaUkAMT2Mbuznm+kAhCJ69E7iigwdd1DS11TJrbsz/PDyZtOojTWfCZ9oRinM4KO32xzYeI1Vc/M6yj/C1kQqCi/G3rKf4UdcxPn2/R5xxjO3itInd8+qMSGEspJPbb7eBgzUJXQHjXqYQVM3JlNFnxHaH8WuyaQ2Y7mFYhcNeVeEwX0IUptJrKMs44icbu5qLpTsmYHcBTsoV1503y5RPY="  # CODACY_PROJECT_TOKEN

script:
  - bundle exec rake spec
  - bundle exec rake rubocop
  - bundle exec rake build:js

deploy:
  - provider: rubygems
    api_key:
      secure: TODO
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
  - provider: npm
    email: jakub@jirutka.cz
    api_key:
      secure: TODO
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
